### ISSUE TITLE
Error while opening

### ISSUE THREAD

**Issue by Stektax** [DamagingRose/Rose-Grabber#132]
I get this error: "python: can't open file 'C:\\Users\\WDAGUtilityAccount\\Desktop\\Rose-Grabber-main\\components\\roseui\\builder.py': [Errno 2] No such file or directory"

**Comment by gumbobr0t** [comment]
fixed

**Comment by Stektax** [comment]
still not working, now i get this error: raceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\Rose-Grabber\components\roseui\builder.py", line 20, in <module>
    from nicegui import ui, app
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\__init__.py", line 8, in <module>
    from . import elements, globals, ui
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\ui.py", line 79, in <module>
    from .elements.line_plot import LinePlot as line_plot
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\elements\line_plot.py", line 3, in <module>
    from .pyplot import Pyplot
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\nicegui\elements\pyplot.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: module not found

**Comment by gumbobr0t** [comment]
you ran install.bat before?

**Comment by Stektax** [comment]
yes

**Comment by Stektax** [comment]
ill try one more time

**Comment by Stektax** [comment]
why is builder.py in the components directory? it should be in roseui right=

**Comment by gumbobr0t** [comment]
let me see

**Comment by gumbobr0t** [comment]
join the dc server we chat there,yeah it should be in roseui

**Comment by gumbobr0t** [comment]
accidently moved it

**Comment by gumbobr0t** [comment]
fixing now

**Comment by Stektax** [comment]
ok i will check, btw discord has an invalid invite

**Comment by gumbobr0t** [comment]
https://discord.gg/nEFngKxJ

should be fixed now tho

**Comment by Stektax** [comment]
wich py ver?

**Comment by gumbobr0t** [comment]
uninstall python and run install.bat, will work then

**Comment by Stektax** [comment]
url in the install script is not accessible: "[https://www.python.org/ftp/python/3.10.13/python-3.10.13-amd64.exe](https://www.python.org/ftp/python/3.10.13/python-3.10.13-amd64.exe)"

**Comment by gumbobr0t** [comment]
uh thanks for providing the issue, should be fixed now

**Comment by Stektax** [comment]
Now still this error, wich i already mentioned above: 
```python
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\Rose-Grabber\components\roseui\builder.py", line 20, in <module>
    from nicegui import ui, app
  File "C:\Program Files\Python311\Lib\site-packages\nicegui\__init__.py", line 8, in <module>
    from . import elements, globals, ui
  File "C:\Program Files\Python311\Lib\site-packages\nicegui\ui.py", line 79, in <module>
    from .elements.line_plot import LinePlot as line_plot
  File "C:\Program Files\Python311\Lib\site-packages\nicegui\elements\line_plot.py", line 3, in <module>
    from .pyplot import Pyplot
  File "C:\Program Files\Python311\Lib\site-packages\nicegui\elements\pyplot.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Program Files\Python311\Lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "C:\Program Files\Python311\Lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: Das angegebene Modul wurde nicht gefunden.
```

**Comment by Stektax** [comment]
fixed by executing: pip install msvc-runtime

**Comment by gumbobr0t** [comment]
ah good thanks for letting me know

**Comment by Stektax** [comment]
also apperantly the web ui is blank: 
![image](https://github.com/DamagingRose/Rose-Grabber/assets/77275742/9037153b-bd8e-4cf4-a805-8cb8a39ad4ad)

**Comment by gumbobr0t** [comment]
pip uninstall components/scrapedata/requirements.txt

**Comment by gumbobr0t** [comment]
then run install.bat again

**Comment by Stektax** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/77275742/b6c5dc2f-7685-4c43-8594-6c3af1cbfc79)

**Comment by gumbobr0t** [comment]
> pip uninstall -r components/scrapedata/requirements.txt

this one should work

**Comment by Stektax** [comment]
still white, the steps worked but eror is still there

**Comment by Stektax** [comment]
trying to install python 3.10

**Comment by gumbobr0t** [comment]
no, python 311 is correct

**Comment by gumbobr0t** [comment]
hmm thats weird

**Comment by gumbobr0t** [comment]
i will do some research

**Comment by Stektax** [comment]
alright

**Comment by Stektax** [comment]
![image](https://github.com/DamagingRose/Rose-Grabber/assets/77275742/aa615c8d-eff1-4fba-a0aa-89d52fab5ae0)
maybe deprecated library?

**Comment by gumbobr0t** [comment]
yeah maybe are some base libs deprecated, maybe wait for an update, but nicegui itself isn't

**Comment by Stektax** [comment]
alright, tried to use the web gui url in the browser but the zip file is empty.

**Comment by gumbobr0t** [comment]
zip file? probably because it didn't finish yet or due to it being opened in browser, try to avoid using the return zip function

**Comment by Stektax** [comment]
i did, this returned the empty zip. can i send any logs for you to analyze?

**Comment by gumbobr0t** [comment]
roselog.log and rosecompile.log

**Comment by gumbobr0t** [comment]
may i get the logs now?

**Comment by gumbobr0t** [comment]
also, this is something completely different than anything i had before, i will need to dig really deep

**Comment by gumbobr0t** [comment]
could you try to completely wipe out your python installation, then reinstall and try visiting `127.0.0.1` in your browser if it still doesn't work then.

**Comment by gumbobr0t** [comment]
closing due to inactivity
